### ISSUE TITLE
Type hint of `send()` input `data` should be `Dict[str, Any]` 

### ISSUE THREAD

**Issue by dineshpinto** [GitBolt/solathon#1]
# Current state
File is`solathon/core/http.py`

```
  def send(self, data: str) -> Dict[str, Any]:
      res = httpx.post(url=self.endpoint, headers=self.headers, json=data)
      return res.json()
```

# Corrected input hint
```
  def send(self, data: Dict[str, Any]) -> Dict[str, Any]:
      res = httpx.post(url=self.endpoint, headers=self.headers, json=data)
      return res.json()
```

This makes sense as `send()`takes the output of `build_data(self, method: str, params: Tuple[Any]) -> Dict[str, Any]`

That said, `res.json()` from `httpx` seems to return `typing.Any` ([source](https://github.com/encode/httpx/blob/2072aa2361a15b69414b917992366421097d7e98/httpx/_models.py#L1200)), so maybe that should be the return?

This is a really cool project btw, I've been looking for a nice Python implementation to play with Solana, happy to contribute more as I go through the code :)

**Comment by GitBolt** [comment]
Thanks for pointing this out! About the second point, I think httpx's `res.json` has the type `typing.Any` since different APIs can return anything, but with Solana's JSON RPC, keys of the JSON are all strings, so maybe it makes more sense to do it like that? What do you think?

**Comment by dineshpinto** [comment]
> but with Solana's JSON RPC, keys of the JSON are all strings, so maybe it makes more sense to do it like that? What do you think?

Makes sense, looking through the Solana JSON RPC API reference you are correct, all JSON returns are of the format `Dict[str, Any]`
